### ISSUE TITLE
Data loading error in tests

### ISSUE THREAD

**Issue by syadlowsky** [cathywu/synthetic-traffic#1]
There seems to be an error running the `test_Los_Angeles_OSM_network.TestLosAngelesOSMNetwork` test:

```
 ........E
 ======================================================================
 ERROR: test_compile (test_Los_Angeles_OSM_network.TestLosAngelesOSMNetwork)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/home/steve/bayen/synthetic-traffic/tests/test_Los_Angeles_OSM_network.py", line 13, in test_compile
     cp = CellPath(NB=150*r,NL=50*r,NS=800*r,TN=LA)
   File "sensors/CellPath.py", line 31, in __init__
     self.sample_from_TN(TN)
   File "sensors/CellPath.py", line 38, in sample_from_TN
     self._sample_from_TN_grid(TN)
   File "sensors/CellPath.py", line 85, in _sample_from_TN_grid
     heavy_points = TN.get_heavy_points(thresh=self.thresh)
   File "networks/LosAngelesOSMNetwork.py", line 19, in get_heavy_points
     roads = pickle.load(open('%s/%s' % (c.DATA_DIR,c.ROAD_FILE)))
 IOError: [Errno 2] No such file or directory: '/home/steve/Dropbox/PhD/traffic-estimation/synthetic_traffic/data/roads.pkl'

 ----------------------------------------------------------------------
 Ran 9 tests in 28.980s

 FAILED (errors=1)
```

**Comment by syadlowsky** [comment]
Oh, now I see the config file. It wasn't particularly clear in the README that this needed to be edited. Also, what directory _should_ this point to?
